# Only care about running tests against latest node
language: node_js
node_js:
- node

# Keep node_modules around, it speeds up builds & they don't change often
cache:
  directories:
  - node_modules
